[package]
name = "fresnel-fir-sandbox"
version.workspace = true
edition.workspace = true

[dependencies]
fresnel-fir-ir = { path = "../fresnel-fir-ir" }
wasmtime.workspace = true
thiserror.workspace = true
serde.workspace = true
anyhow = "1"

[dev-dependencies]
wat.workspace = true
