[package]
name = "beacon-compiler"
version.workspace = true
edition.workspace = true

[dependencies]
beacon-ir = { path = "../beacon-ir" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
