[package]
name = "beacon-sandbox"
version.workspace = true
edition.workspace = true

[dependencies]
beacon-ir = { path = "../beacon-ir" }
wasmtime.workspace = true
thiserror.workspace = true
serde.workspace = true
anyhow = "1"

[dev-dependencies]
wat.workspace = true
